### ISSUE TITLE
Commented out 'customMessage' and 'Note' fields in the RSVP plugin back-end.

### ISSUE THREAD

**Issue by Kenuzara** [medelibero/Wordpress-RSVP-Plugin#13]
In the RSVP Plugin top-page (where one sees the list of attendees), the columns for 'customMessage' and 'Note' have been commented out in the latest update, despite not having any changelog message for this change. 

File name that has been changed is 'wp-rsvp.php'.

**Comment by medelibero** [comment]
Ok. Do you want the fields to be surfaced again?

**Comment by Kenuzara** [comment]
Hi, sorry for not replying sooner, I was out of town. 

Yes, it'd be great to surface the fields again. There was no change-log giving a reason for why they were removed, and the note field is very handy to have (About half the responses to date on my wedding site have made use of the note field).

**Comment by medelibero** [comment]
Do you just want the "note" field or do you want the custom message as well?

**Comment by Kenuzara** [comment]
I was only using the note field, but I can't speak for anyone else.

**Comment by medelibero** [comment]
I just released 2.1.3 which has the note field surfaced.

**Comment by Kenuzara** [comment]
Thanks for re-surfacing the note field. :+1:  :smile:
